// $Id: TextType.h,v 1.4.2.1 2001/07/05 23:32:33 serge Exp $
//
// Copyright (c)1999-2001 Aladdin Systems, Inc. All Rights Reserved.
// 245 Westridge Drive, Watsonville, CA 95076, USA
// http://www.aladdinsys.com/
// 1-831-761-6200
//
// This source code and specific concepts contained herein are confidential
// information and property of Aladdin Systems. Distribution is prohibited
// without written permission of Aladdin Systems.

#if !defined stuffit5_TextType_h_included
#define stuffit5_TextType_h_included

#include "un/config.h"

#if defined __cplusplus

/** Text type.

<p>Describes text file formats.

<p>Different operating systems use different characters or combinations of
characters to indicate an end-of-line in a text file. Unix uses LF (line feed
character), DOS and Windows use the CR-LF (carriage return, line feed) pair,
MacOS uses CR (carriage return) only.

<p>StuffIt readers can convert files that are being decompressed or decoded to
different text formats. A <code>stuffit5::TextType</code> determines
what type of text is output after the conversion.

<p>A <code>stuffit5::TextType</code> can also determine the type of
encoded text generated by Uuencode and BinHex encoders.

@author serge@aladdinsys.com
@version $Revision: 1.4.2.1 $, $Date: 2001/07/05 23:32:33 $
*/

namespace stuffit5 {
    namespace TextType {
        /** Underlying type. */
        typedef int type;

        /** The text file format with line feed (LF) end-of-lines. */
        const stuffit5::TextType::type lf = 1;

        /** The text file format with carriage return (CR) end-of-lines. */
        const stuffit5::TextType::type cr = 2;

        /** The text file format with carriage return (CR) and line feed (LF)
        end-of-lines. */
        const stuffit5::TextType::type crlf = 3;

        /** The UNIX text file format with line feed (LF) end-of-lines. */
        const stuffit5::TextType::type unixx = 1;

        /** The Macintosh text file format with carriage return (CR) end-of-lines. */
        const stuffit5::TextType::type mac = 2;

        /** The DOS/Windows text file format with carriage return (CR) and line feed
        (LF) end-of-lines. */
        const stuffit5::TextType::type windows = 3;

        /** The text file format of the operating system on which the engine is running. */
        #if platform_win32 || platform_cygwin
            const stuffit5::TextType::type native = windows;
        #elif platform_macintosh
            const stuffit5::TextType::type native = mac;
        #else
            const stuffit5::TextType::type native = unixx;
        #endif
    }
}

#endif // __cplusplus

#if !defined __cplusplus || defined stuffit5_implementation

#include "stuffit5/common.h"

/** C equivalent of <code>stuffit5::TextType::lf</code>. */
const stuffit5_TextType_type stuffit5_TextType_lf = 1;
/** C equivalent of <code>stuffit5::TextType::cr</code>. */
const stuffit5_TextType_type stuffit5_TextType_cr = 2;
/** C equivalent of <code>stuffit5::TextType::crlf</code>. */
const stuffit5_TextType_type stuffit5_TextType_crlf = 3;

/** C equivalent of <code>stuffit5::TextType::unixx</code>. */
const stuffit5_TextType_type stuffit5_TextType_unixx = 1;
/** C equivalent of <code>stuffit5::TextType::mac</code>. */
const stuffit5_TextType_type stuffit5_TextType_mac = 2;
/** C equivalent of <code>stuffit5::TextType::windows</code>. */
const stuffit5_TextType_type stuffit5_TextType_windows = 3;

#if platform_win32 || platform_cygwin
    /** C equivalent of <code>stuffit5::TextType::native</code>. */
    const stuffit5_TextType_type stuffit5_TextType_native = 3;
#elif platform_macintosh
    const stuffit5_TextType_type stuffit5_TextType_native = 2;
#else
    const stuffit5_TextType_type stuffit5_TextType_native = 1;
#endif

#endif // __cplusplus

#endif

