// $Id: FileDeleteListener.h,v 1.3.2.1 2001/07/05 23:32:35 serge Exp $
//
// Copyright (c)1999-2001 Aladdin Systems, Inc. All Rights Reserved.
// 245 Westridge Drive, Watsonville, CA 95076, USA
// http://www.aladdinsys.com/
// 1-831-761-6200
//
// This source code and specific concepts contained herein are confidential
// information and property of Aladdin Systems. Distribution is prohibited
// without written permission of Aladdin Systems.

#if !defined stuffit5_event_FileDeleteListener_h_included
#define stuffit5_event_FileDeleteListener_h_included

/** Event handler for incomplete files or archives.

<p>This event callback is invoked to ask whether an incomplete or incorrect file
generated by a reader or an unfinished archive created by a writer should be
deleted.

@author serge@aladdinsys.com
@version $Revision: 1.3.2.1 $, $Date: 2001/07/05 23:32:35 $
@see stuffit5::Writer
*/

#if defined __cplusplus

#include "stuffit5/event/Listener.h"

namespace stuffit5 {
    namespace event {
        class FileDeleteListener : public stuffit5::event::Listener {
        public:
            /** Default constructor. */
            FileDeleteListener() {
            }

            /** Destructor. */
            virtual ~FileDeleteListener() {
            }

            /** An incomplete file or archive.

            <p>This pure virtual member function is the event callback invoked to handle
            an incomplete or incorrect file or an unfinished archive.

            @return <code>true</code> to delete the file, <code>false</code> to keep it
            */
            virtual bool fileDeleteEvent() = 0;
        };
    }
}

#endif

#if !defined __cplusplus || defined stuffit5_implementation

#include "un/config.h"
#include "stuffit5/common.h"

typedef bool (*stuffit5_event_FileDeleteListener_fileDeleteEvent)(stuffit5_Reader reader);
//typedef bool (*stuffit5_event_FileDeleteListener_fileDeleteEvent)(stuffit5_Writer writer);

extern_c exported stuffit5_event_FileDeleteListener stuffit5_Reader_addFileDeleteListener(stuffit5_event_FileDeleteListener_fileDeleteEvent fileDeleteEvent, stuffit5_Reader reader);
extern_c exported void stuffit5_Reader_removeFileDeleteListener(stuffit5_event_FileDeleteListener fileDeleteListener, stuffit5_Reader reader);

extern_c exported stuffit5_event_FileDeleteListener stuffit5_Writer_addFileDeleteListener(stuffit5_event_FileDeleteListener_fileDeleteEvent fileDeleteEvent, stuffit5_Writer writer);
extern_c exported void stuffit5_Writer_removeFileDeleteListener(stuffit5_event_FileDeleteListener fileDeleteListener, stuffit5_Writer writer);

#endif

#endif

